package pl.szynolandia.singerstats;

import android.content.*;
import android.graphics.*;
import android.net.*;
import android.os.*;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.*;
import java.util.*;

public class PublicationPlannerView extends LinearLayout {
    interface SongProvider{String get();}
    MainActivityV2 a; SongProvider song; ArrayList<Entry> rows=new ArrayList<>(); int selected=-1; LinearLayout list,editor; final int FG=Color.rgb(235,235,235);
    static class Entry{String status="Pomysł",material="",date="",time="18:00",title="",description="",hashtags="",notes="";
        JSONObject json()throws Exception{JSONObject o=new JSONObject();o.put("status",status);o.put("material",material);o.put("date",date);o.put("time",time);o.put("title",title);o.put("description",description);o.put("hashtags",hashtags);o.put("notes",notes);return o;}
        static Entry from(JSONObject o){Entry e=new Entry();e.status=o.optString("status","Pomysł");e.material=o.optString("material","");e.date=o.optString("date","");e.time=o.optString("time","18:00");e.title=o.optString("title","");e.description=o.optString("description","");e.hashtags=o.optString("hashtags","");e.notes=o.optString("notes","");return e;}}
    PublicationPlannerView(MainActivityV2 c,SongProvider s){super(c);a=c;song=s;setOrientation(VERTICAL);setPadding(6,6,6,20);load();build();}
    TextView tx(String s,int z){TextView v=new TextView(a);v.setText(s);v.setTextColor(FG);v.setTextSize(z);v.setPadding(7,7,7,7);return v;}
    Button bt(String s){Button b=new Button(a);b.setText(s);b.setAllCaps(false);return b;}
    LinearLayout rr(){LinearLayout r=new LinearLayout(a);r.setOrientation(HORIZONTAL);return r;}
    EditText ed(String s,boolean multi){EditText e=new EditText(a);e.setTextColor(FG);e.setText(s);e.setSingleLine(!multi);if(multi)e.setMinLines(3);return e;}
    String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    Entry blank(String material){Entry e=new Entry();e.material=material==null?"":material;e.title=e.material;e.date=today();return e;}
    void build(){removeAllViews();TextView h=tx("PLAN PUBLIKACJI / NOTATKI",20);h.setTypeface(null,Typeface.BOLD);addView(h);TextView info=tx("Plan zapisuje się niezależnie od .ssp.json. Ten sam zestaw pól i operacji co na Windows/Linux.",13);addView(info);
        HorizontalScrollView hs=new HorizontalScrollView(a);LinearLayout bar=rr();String[] labs={"+ Dodaj","+ Bieżący utwór","Duplikuj","Usuń","Eksport CSV","Import CSV"};for(String s:labs){Button b=bt(s);bar.addView(b);if(s.equals("+ Dodaj"))b.setOnClickListener(v->addEntry(""));else if(s.equals("+ Bieżący utwór"))b.setOnClickListener(v->addEntry(song.get()));else if(s.equals("Duplikuj"))b.setOnClickListener(v->duplicate());else if(s.equals("Usuń"))b.setOnClickListener(v->delete());else if(s.equals("Eksport CSV"))b.setOnClickListener(v->exportCsv());else b.setOnClickListener(v->a.openCsvForPlanner());}hs.addView(bar);addView(hs);
        list=new LinearLayout(a);list.setOrientation(VERTICAL);addView(list);editor=new LinearLayout(a);editor.setOrientation(VERTICAL);addView(editor);render();}
    void addEntry(String m){rows.add(blank(m==null?"":m.trim()));selected=rows.size()-1;save();render();}
    void duplicate(){if(selected<0||selected>=rows.size())return;Entry x=rows.get(selected),n=new Entry();n.status="Pomysł";n.material=x.material;n.date=x.date;n.time=x.time;n.title=x.title;n.description=x.description;n.hashtags=x.hashtags;n.notes=x.notes;rows.add(selected+1,n);selected++;save();render();}
    void delete(){if(selected<0||selected>=rows.size())return;new AlertDialog.Builder(a).setTitle("Usuń wpis").setMessage("Usunąć wybrany wpis?").setPositiveButton("Usuń",(d,w)->{rows.remove(selected);selected=Math.min(selected,rows.size()-1);save();render();}).setNegativeButton("Anuluj",null).show();}
    void render(){list.removeAllViews();for(int i=0;i<rows.size();i++){final int ix=i;Entry e=rows.get(i);Button b=bt((i+1)+". ["+e.status+"] "+(e.material.isEmpty()?e.title:e.material)+"  •  "+e.date+" "+e.time);if(i==selected)b.setBackgroundColor(Color.rgb(65,70,90));b.setOnClickListener(v->{selected=ix;render();});list.addView(b);}renderEditor();}
    void renderEditor(){editor.removeAllViews();if(selected<0||selected>=rows.size()){editor.addView(tx("Dodaj wpis albo wybierz istniejący.",13));return;}Entry e=rows.get(selected);
        Spinner st=new Spinner(a);String[] statuses={"Pomysł","W przygotowaniu","Gotowe","Zaplanowane","Wrzucone"};st.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,statuses));int si=Arrays.asList(statuses).indexOf(e.status);st.setSelection(Math.max(0,si));editor.addView(tx("Status",13));editor.addView(st);
        EditText material=ed(e.material,false),date=ed(e.date,false),time=ed(e.time,false),title=ed(e.title,false),desc=ed(e.description,true),tags=ed(e.hashtags,false),notes=ed(e.notes,true);
        editor.addView(tx("Utwór / materiał",13));editor.addView(material);LinearLayout dt=rr();dt.addView(date,new LayoutParams(0,-2,1));dt.addView(time,new LayoutParams(0,-2,1));editor.addView(tx("Data / godzina",13));editor.addView(dt);editor.addView(tx("Tytuł",13));editor.addView(title);editor.addView(tx("Opis",13));editor.addView(desc);editor.addView(tx("Hashtagi",13));editor.addView(tags);editor.addView(tx("Notatki",13));editor.addView(notes);
        Button saveBtn=bt("Zapisz zmiany");editor.addView(saveBtn);saveBtn.setOnClickListener(v->{e.status=(String)st.getSelectedItem();e.material=material.getText().toString();e.date=date.getText().toString();e.time=time.getText().toString();e.title=title.getText().toString();e.description=desc.getText().toString();e.hashtags=tags.getText().toString();e.notes=notes.getText().toString();save();render();Toast.makeText(a,"Zapisano",Toast.LENGTH_SHORT).show();});
        LinearLayout cp=rr();Button c1=bt("Kopiuj tytuł"),c2=bt("Kopiuj opis"),c3=bt("Kopiuj #"),c4=bt("Kopiuj wszystko");cp.addView(c1);cp.addView(c2);cp.addView(c3);cp.addView(c4);HorizontalScrollView ch=new HorizontalScrollView(a);ch.addView(cp);editor.addView(ch);c1.setOnClickListener(v->copy(title.getText().toString()));c2.setOnClickListener(v->copy(desc.getText().toString()));c3.setOnClickListener(v->copy(tags.getText().toString()));c4.setOnClickListener(v->copy(join(title.getText().toString(),desc.getText().toString(),tags.getText().toString())));
    }
    String join(String...x){StringBuilder b=new StringBuilder();for(String s:x)if(s!=null&&!s.trim().isEmpty()){if(b.length()>0)b.append("\n\n");b.append(s.trim());}return b.toString();}
    void copy(String s){ClipboardManager cm=(ClipboardManager)a.getSystemService(Context.CLIPBOARD_SERVICE);cm.setPrimaryClip(ClipData.newPlainText("TikTok",s==null?"":s));Toast.makeText(a,"Skopiowano",Toast.LENGTH_SHORT).show();}
    File store(){return new File(a.getFilesDir(),"publication_planner.json");}
    void save(){try{JSONObject r=new JSONObject();r.put("version",1);JSONArray ar=new JSONArray();for(Entry e:rows)ar.put(e.json());r.put("entries",ar);try(OutputStream o=new FileOutputStream(store())){o.write(r.toString(2).getBytes("UTF-8"));}}catch(Exception ignored){}}
    void load(){try{File f=store();if(!f.exists())return;ByteArrayOutputStream o=new ByteArrayOutputStream();try(InputStream in=new FileInputStream(f)){byte[]b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);}JSONObject r=new JSONObject(o.toString("UTF-8"));JSONArray ar=r.optJSONArray("entries");if(ar!=null)for(int i=0;i<ar.length();i++)rows.add(Entry.from(ar.optJSONObject(i)));}catch(Exception ignored){}}
    String csvCell(String s){if(s==null)s="";return "\""+s.replace("\"","\"\"").replace("\r","")+"\"";}
    void exportCsv(){try{StringBuilder b=new StringBuilder("status;material;date;time;title;description;hashtags;notes\n");for(Entry e:rows)b.append(csvCell(e.status)).append(';').append(csvCell(e.material)).append(';').append(csvCell(e.date)).append(';').append(csvCell(e.time)).append(';').append(csvCell(e.title)).append(';').append(csvCell(e.description)).append(';').append(csvCell(e.hashtags)).append(';').append(csvCell(e.notes)).append('\n');String name="plan_publikacji_"+new SimpleDateFormat("yyyyMMdd_HHmm",Locale.US).format(new Date())+".csv";ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,name);v.put(MediaStore.Downloads.MIME_TYPE,"text/csv");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Downloads.RELATIVE_PATH,"Download/Singer Stats Visualizer");Uri u=a.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);try(OutputStream o=a.getContentResolver().openOutputStream(u)){o.write(b.toString().getBytes("UTF-8"));}Toast.makeText(a,"CSV zapisany w Pobranych",Toast.LENGTH_LONG).show();}catch(Exception ex){new AlertDialog.Builder(a).setTitle("Eksport CSV").setMessage(ex.toString()).setPositiveButton("OK",null).show();}}
    public void importCsv(Uri u){try{String text;try(InputStream in=a.getContentResolver().openInputStream(u)){ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]bb=new byte[8192];int n;while((n=in.read(bb))>0)o.write(bb,0,n);text=o.toString("UTF-8");}ArrayList<String[]> parsed=parseCsv(text);int added=0;for(int i=1;i<parsed.size();i++){String[] c=parsed.get(i);if(c.length<1)continue;Entry e=blank("");if(c.length>0)e.status=c[0];if(c.length>1)e.material=c[1];if(c.length>2)e.date=c[2];if(c.length>3)e.time=c[3];if(c.length>4)e.title=c[4];if(c.length>5)e.description=c[5];if(c.length>6)e.hashtags=c[6];if(c.length>7)e.notes=c[7];rows.add(e);added++;}save();render();Toast.makeText(a,"Import CSV: "+added+" wpisów",Toast.LENGTH_LONG).show();}catch(Exception ex){new AlertDialog.Builder(a).setTitle("Import CSV").setMessage(ex.toString()).setPositiveButton("OK",null).show();}}
    ArrayList<String[]> parseCsv(String s){ArrayList<String[]> out=new ArrayList<>();ArrayList<String> row=new ArrayList<>();StringBuilder cell=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='\"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='\"'){cell.append('\"');i++;}else q=!q;}else if(c==';'&&!q){row.add(cell.toString());cell.setLength(0);}else if((c=='\n'||c=='\r')&&!q){if(c=='\r'&&i+1<s.length()&&s.charAt(i+1)=='\n')i++;row.add(cell.toString());cell.setLength(0);out.add(row.toArray(new String[0]));row.clear();}else cell.append(c);}if(cell.length()>0||!row.isEmpty()){row.add(cell.toString());out.add(row.toArray(new String[0]));}return out;}
}
